window.gigs = [
  // 2025
  { date: "13.09.2025", venue: "Suisto", city: "Hämeenlinna", country: "Finland" },
  { date: "12.09.2025", venue: "Krapin Paja", city: "Tuusula", country: "Finland" },
  { date: "05.09.2025", venue: "Tulisuudelma", city: "Vantaa", country: "Finland" },
  { date: "04.09.2025", venue: "Sellosali", city: "Espoo", country: "Finland" },
  { date: "30.08.2025", venue: "Linnanvirta puistojuhla", city: "Kajaani", country: "Finland" },
  { date: "29.08.2025", venue: "Höyhtyän Ostarifestari VI", city: "Oulu", country: "Finland" },
  { date: "09.08.2025", venue: "Tampere City Festival", city: "Tampere", country: "Finland" },
  { date: "01.08.2025", venue: "Tavastia", city: "Helsinki", country: "Finland" },
  { date: "05.07.2025", venue: "Ilovaari", city: "Joensuu", country: "Finland" },
  { date: "14.06.2025", venue: "Helsinki City Festival", city: "Helsinki", country: "Finland" },
  { date: "14.03.2025", venue: "Pensselitehdas", city: "Porvoo", country: "Finland" },
  { date: "09.03.2025", venue: "Porin Teatteri", city: "Pori", country: "Finland" },
  { date: "08.03.2025", venue: "G Live Lab", city: "Tampere", country: "Finland" },
  { date: "01.03.2025", venue: "Ääniwalli", city: "Helsinki", country: "Finland" },
  { date: "28.02.2025", venue: "Kulttuurikuppila Brummi", city: "Rauma", country: "Finland" },
  { date: "22.02.2025", venue: "Maxim", city: "Kuopio", country: "Finland" },
  { date: "21.02.2025", venue: "Hyvinkääsali", city: "Hyvinkää", country: "Finland" },
  { date: "04.02.2025", venue: "Puoli seitsemän,<BR>YLE TV1 (TV)", city: "Helsinki", country: "Finland" },
  { date: "26.01.2025", venue: "M/S Kesärauha", city: "Viking Grace", country: "Finland" },

  // 2022
  { date: "27.08.2022", venue: "Leipätehdas, (Private)", city: "Helsinki", country: "Finland" },
  { date: "01.07.2022", venue: "Provinssi", city: "Seinäjoki", country: "Finland" },

  // 2021
  { date: "30.10.2021", venue: "Tavastia", city: "Helsinki", country: "Finland" },
  { date: "29.10.2021", venue: "Apollo", city: "Turku", country: "Finland" },
  { date: "23.10.2021", venue: "Rytmikorjaamo", city: "Seinäjoki", country: "Finland" },
  { date: "22.10.2021", venue: "Olympia", city: "Tampere", country: "Finland" },
  { date: "16.10.2021", venue: "Kerubi", city: "Joensuu", country: "Finland" },
  { date: "15.10.2021", venue: "Sawohouse Underground", city: "Kuopio", country: "Finland" },
  { date: "09.10.2021", venue: "Sellosali", city: "Espoo", country: "Finland" },
  { date: "06.08.2021", venue: "Kesärauha", city: "Turku", country: "Finland" },
  { date: "30.07.2021", venue: "Qstock", city: "Oulu", country: "Finland" },
  { date: "15.04.2021", venue: "The Juice Show (Stream)", city: "Helsinki", country: "Finland" },
  { date: "09.04.2021", venue: "Fafa's Replugged (Stream)", city: "Helsinki", country: "Finland" },
  // 2012
  { date: "16.03.2012", venue: "Hullu Poro Areena", city: "Sirkka", country: "Finland" },
  { date: "04.02.2012", venue: "House of Rock", city: "Kouvola", country: "Finland" },
  { date: "03.02.2012", venue: "Tavastia", city: "Helsinki", country: "Finland" },

  // 2011
  { date: "26.11.2011", venue: "Dyyni", city: "Kalajoki", country: "Finland" },
  { date: "25.11.2011", venue: "West Coast Bar", city: "Kokkola", country: "Finland" },
  { date: "24.11.2011", venue: "45 Special", city: "Oulu", country: "Finland" },
  { date: "18.11.2011", venue: "Freetime", city: "Jyväskylä", country: "Finland" },
  { date: "17.11.2011", venue: "Yo-talo", city: "Tampere", country: "Finland" },
  { date: "12.11.2011", venue: "Rytmikorjaamo", city: "Seinäjoki", country: "Finland" },
  { date: "11.11.2011", venue: "Royal Night Club", city: "Vaasa", country: "Finland" },
  { date: "29.10.2011", venue: "Kerubi", city: "Joensuu", country: "Finland" },
  { date: "27.10.2011", venue: "Henry's Pub", city: "Kuopio", country: "Finland" },
  { date: "22.10.2011", venue: "Virgin Oil Co.", city: "Helsinki", country: "Finland" },
  { date: "15.10.2011", venue: "Apollo", city: "Turku", country: "Finland" },
  { date: "14.10.2011", venue: "Apollo Live Club", city: "Rauma", country: "Finland" },

  // 2007
  { date: "01.11.2007", venue: "On The Rocks", city: "Helsinki", country: "Finland" },
  { date: "21.09.2007", venue: "Virgin Oil Co.", city: "Helsinki", country: "Finland" },
  { date: "11.05.2007", venue: "SKT, (private)", city: "Lappeenranta", country: "Finland" },
  { date: "30.04.2007", venue: "Doris Night, Hotelli Lappee", city: "Lappeenranta", country: "Finland" },
  { date: "20.01.2007", venue: "Virgin Oil Co.", city: "Helsinki", country: "Finland" },

  // 2006
  { date: "28.10.2006", venue: "Musiikki & Media, Klubi", city: "Tampere", country: "Finland" },
  { date: "21.10.2006", venue: "NRJ Fashion Awards,<BR>Kaapelitehdas", city: "Helsinki", country: "Finland" },
  { date: "26.08.2006", venue: "Kesäpotpuri, Pakkahuone", city: "Tampere", country: "Finland" },
  { date: "12.08.2006", venue: "Meijerirock", city: "Espoo", country: "Finland" },
  { date: "29.07.2006", venue: "Qstock", city: "Oulu", country: "Finland" },
  { date: "28.07.2006", venue: "Down By The Kemijoki,<BR>Tivoli", city: "Rovaniemi", country: "Finland" },
  { date: "26.05.2006", venue: "Stockholm Diskotek", city: "Helsinki", country: "Finland" },
  { date: "10.05.2006", venue: "Giggling Marlin", city: "Turku", country: "Finland" },
  { date: "08.05.2006", venue: "Mobile Monday,<BR>Wanha satama", city: "Helsinki", country: "Finland" },
  { date: "06.05.2006", venue: "Night Club Riviera", city: "Kouvola", country: "Finland" },
  { date: "05.05.2006", venue: "Amarillo", city: "Kotka", country: "Finland" },
  { date: "30.04.2006", venue: "Hangon Casino", city: "Hanko", country: "Finland" },
  { date: "26.04.2006", venue: "Giggling Marlin", city: "Vaasa", country: "Finland" },
  { date: "19.04.2006", venue: "Tavastia", city: "Helsinki", country: "Finland" },
  { date: "14.04.2006", venue: "Kharma", city: "Jyväskylä", country: "Finland" },
  { date: "08.04.2006", venue: "Ravintola Konsta", city: "Kaustinen", country: "Finland" },
  { date: "07.04.2006", venue: "YO-talo", city: "Tampere", country: "Finland" },
  { date: "06.04.2006", venue: "Happytime Baari", city: "Savonlinna", country: "Finland" },
  { date: "05.04.2006", venue: "Henry's Pub", city: "Kuopio", country: "Finland" },
  { date: "02.04.2006", venue: "Kulttuuritalo,<BR>(Simple Minds support)", city: "Helsinki", country: "Finland" },
  { date: "01.04.2006", venue: "Stockmann (unplugged)", city: "Helsinki", country: "Finland" },
  { date: "30.03.2006", venue: "Tuomas & Juuso Experience,<BR>Nelonen (TV, unplugged)", city: "Helsinki", country: "Finland" },
  { date: "29.03.2006", venue: "Pop Klubi,<BR>YLE TV2 (TV)", city: "Helsinki", country: "Finland" },
  { date: "28.03.2006", venue: "Popstudio,<BR>YLE / YleQ,(Radio, unplugged)", city: "Helsinki", country: "Finland" },
  { date: "24.03.2006", venue: "Kuudes linja,<BR>(album release)", city: "Helsinki", country: "Finland" },

  // 2005
  { date: "22.04.2005", venue: "Palatsi, (Private)", city: "Turku", country: "Finland" },
  { date: "09.04.2005", venue: "Tivoli 15 -vuotta", city: "Rovaniemi", country: "Finland" },
  { date: "06.02.2005", venue: "Goom-risteily", city: "M/S Romantika", country: "Finland" },
  { date: "08.01.2005", venue: "Hyväntekeväisyyskonsertti<BR>Aasian katastrofin uhrien hyväksi,<BR>Nosturi", city: "Helsinki", country: "Finland" },

  // 2004
  { date: "18.12.2004", venue: "Tavastia", city: "Helsinki", country: "Finland" },
  { date: "17.12.2004", venue: "Sokos Hotel Rikala", city: "Salo", country: "Finland" },
  { date: "16.12.2004", venue: "Kåren", city: "Turku", country: "Finland" },
  { date: "08.12.2004", venue: "Hotelli Lakeus", city: "Seinäjoki", country: "Finland" },
  { date: "02.12.2004", venue: "Hullu Poro Areena", city: "Sirkka", country: "Finland" },
  { date: "01.12.2004", venue: "Hullu Poro Areena", city: "Sirkka", country: "Finland" },
  { date: "13.10.2004", venue: "Hewlett Packard (private)", city: "Espoo", country: "Finland" },
  { date: "07.10.2004", venue: "Ravintola Fever", city: "Jyväskylä", country: "Finland" },
  { date: "14.09.2004", venue: "Vulcanalia", city: "Oulu", country: "Finland" },
  { date: "09.09.2004", venue: "Alvarin aukio", city: "Espoo", country: "Finland" },
  { date: "28.08.2004", venue: "Ravintola Jonathan", city: "Hanko", country: "Finland" },
  { date: "24.08.2004", venue: "Pikku-Vesijärven puisto", city: "Lahti", country: "Finland" },
  { date: "01.08.2004", venue: "Ankkarock", city: "Vantaa", country: "Finland" },
  { date: "30.07.2004", venue: "Hotelli Lappee / Doris", city: "Lappeenranta", country: "Finland" },
  { date: "29.07.2004", venue: "Kaivohuone Club", city: "Helsinki", country: "Finland" },
  { date: "23.07.2004", venue: "QStock Festival", city: "Oulu", country: "Finland" },
  { date: "18.07.2004", venue: "Ilosaarirock", city: "Joensuu", country: "Finland" },
  { date: "17.07.2004", venue: "Terwapop", city: "Kuortane", country: "Finland" },
  { date: "16.07.2004", venue: "Rockperry Festival", city: "Vaasa", country: "Finland" },
  { date: "10.07.2004", venue: "Ruisrock", city: "Turku", country: "Finland" },
  { date: "03.07.2004", venue: "Räyhärock", city: "Loviisa", country: "Finland" },
  { date: "26.06.2004", venue: "Kalajoen Juhannus Festival", city: "Kalajoki", country: "Finland" },
  { date: "25.06.2004", venue: "Himos Festival", city: "Jämsä", country: "Finland" },
  { date: "25.06.2004", venue: "Midnight Party Planet,<BR>Tykkimäki", city: "Kouvola", country: "Finland" },
  { date: "19.06.2004", venue: "Provinssirock", city: "Seinäjoki", country: "Finland" },
  { date: "28.05.2004", venue: "FinnFest", city: "Hamburg", country: "Germany" },
  { date: "12.05.2004", venue: "Ruma-klubi, Tavastia", city: "Helsinki", country: "Finland" },
  { date: "08.05.2004", venue: "Nevada", city: "Porvoo", country: "Finland" },
  { date: "06.05.2004", venue: "Panama Jack", city: "Kerava", country: "Finland" },
  { date: "01.05.2004", venue: "Tivoli", city: "Rovaniemi", country: "Finland" },
  { date: "30.04.2004", venue: "Umpitunneli", city: "Tornio", country: "Finland" },
  { date: "29.04.2004", venue: "45 Special", city: "Oulu", country: "Finland" },
  { date: "28.04.2004", venue: "Henry's Pub", city: "Kuopio", country: "Finland" },
  { date: "24.04.2004", venue: "Kultainen Kukko", city: "Kankaanpää", country: "Finland" },
  { date: "23.04.2004", venue: "Duuni", city: "Seinäjoki", country: "Finland" },
  { date: "22.04.2004", venue: "Radisson SAS Royal Hotel", city: "Vaasa", country: "Finland" },
  { date: "21.04.2004", venue: "RT Party House", city: "Järvenpää", country: "Finland" },
  { date: "17.04.2004", venue: "Klubi", city: "Hyvinkää", country: "Finland" },
  { date: "16.04.2004", venue: "Klubi", city: "Turku", country: "Finland" },
  { date: "10.04.2004", venue: "Tapiola Garden", city: "Espoo", country: "Finland" },
  { date: "08.04.2004", venue: "YO-talo", city: "Tampere", country: "Finland" },
  { date: "09.04.2004", venue: "Nite Train", city: "Imatra", country: "Finland" },
  { date: "31.03.2004", venue: "City-Anttila Megastore", city: "Helsinki", country: "Finland" },
  { date: "26.03.2004", venue: "Tulisuudelma,<BR>Radio Suomipop -bileet", city: "Vantaa", country: "Finland" },
  { date: "25.03.2004", venue: "Hyppönen Enbuske Experience,<BR>Nelonen (TV, unplugged)", city: "Helsinki", country: "Finland" },
  { date: "20.03.2004", venue: "SubTV Sessions,<BR>(TV, unplugged)", city: "Helsinki", country: "Finland" },

  // 2003
  { date: "11.07.2003", venue: "Lappeenranta Festivals", city: "Lappeenranta", country: "Finland" },
  { date: "07.06.2003", venue: "DBTL", city: "Turku", country: "Finland" },
  { date: "20.03.2003", venue: "Ravintola Nunu", city: "Jyväskylä", country: "Finland" },
  { date: "20.02.2003", venue: "Nouveau Casino", city: "Paris", country: "France" },
  { date: "18.02.2003", venue: "3GSM World Congress,<BR>Casino Barriere Le Croisette", city: "Cannes", country: "France" },
  { date: "09.02.2003", venue: "Goom-risteily,<BR>Viking Cinderella", city: "Viking Cinderella", country: "Finland" },
  { date: "25.01.2003", venue: "Nuorisoseurantalo", city: "Mietaa", country: "Finland" },
  { date: "16.01.2003", venue: "Nova-klubi", city: "Silja Europa", country: "Finland" },

  // 2002
  { date: "14.12.2002", venue: "Nosturi", city: "Helsinki", country: "Finland" },
  { date: "13.12.2002", venue: "Säätämö", city: "Turku", country: "Finland" },
  { date: "06.12.2002", venue: "Popfinlandia III, Jäähalli", city: "Helsinki", country: "Finland" },
  { date: "05.12.2002", venue: "Klubi", city: "Tampere", country: "Finland" },
  { date: "04.12.2002", venue: "Lutakko", city: "Jyväskylä", country: "Finland" },
  { date: "29.11.2002", venue: "Urheilutalo", city: "Riihimäki", country: "Finland" },
  { date: "28.11.2002", venue: "Sipuli (private)", city: "Helsinki", country: "Finland" },
  { date: "23.11.2002", venue: "Club B-52", city: "Ähtäri", country: "Finland" },
  { date: "22.11.2002", venue: "Musiikkikeskus", city: "Kuopio", country: "Finland" },
  { date: "19.11.2002", venue: "Myyrmannin muistokonsertti,<BR>Myyrmäkihalli", city: "Vantaa", country: "Finland" },
  { date: "15.11.2002", venue: "Rubin 2000", city: "Kouvola", country: "Finland" },
  { date: "13.11.2002", venue: "Ruma-klubi, Tavastia", city: "Helsinki", country: "Finland" },
  { date: "01.11.2002", venue: "Toisto-klubi,<BR>Hotelli Ellivuori", city: "Vammala", country: "Finland" },
  { date: "02.11.2002", venue: "Amarillo", city: "Vaasa", country: "Finland" },
  { date: "26.10.2002", venue: "Red Club", city: "St. Petersburg", country: "Russia" },
  { date: "18.10.2002", venue: "Nevada", city: "Porvoo", country: "Finland" },
  { date: "10.10.2002", venue: "Morning Glory,<BR> MTV Nordic (TV)", city: "Stockholm", country: "Sweden" },
  { date: "28.09.2002", venue: "Akateeminen Startti", city: "Kuopio", country: "Finland" },
  { date: "20.09.2002", venue: "Nosturi (private)", city: "Helsinki", country: "Finland" },
  { date: "12.09.2002", venue: "MTV3 Live Makasiineilla (TV)", city: "Helsinki", country: "Finland" },
  { date: "03.09.2002", venue: "HP Bazaar Camp,<BR>Shangri-La Hotel", city: "Beijing", country: "China" },
  { date: "17.08.2002", venue: "Rock The Globe", city: "Kuopio", country: "Finland" },
  { date: "10.08.2002", venue: "Välipuistorock", city: "Lapua", country: "Finland" },
  { date: "09.08.2002", venue: "Kulttuurikeskus Poleeni", city: "Pieksämäki", country: "Finland" },
  { date: "08.08.2002", venue: "On The Rocks", city: "Helsinki", country: "Finland" },
  { date: "27.07.2002", venue: "Koneisto", city: "Helsinki", country: "Finland" },
  { date: "26.07.2002", venue: "Down By The Kemijoki", city: "Rovaniemi", country: "Finland" },
  { date: "20.07.2002", venue: "Tammerfest", city: "Tampere", country: "Finland" },
  { date: "13.07.2002", venue: "Aitoon Kirkastusjuhlat", city: "Aitoo", country: "Finland" },
  { date: "12.07.2002", venue: "Jyväskylän Kesä", city: "Jyväskylä", country: "Finland" },
  { date: "07.07.2002", venue: "Ruisrock", city: "Turku", country: "Finland" },
  { date: "01.07.2002", venue: "Popsmart,<BR>YLE FST (TV)", city: "Helsinki", country: "Finland" },
  { date: "14.06.2002", venue: "Feenix", city: "Turku", country: "Finland" },
  { date: "12.06.2002", venue: "Kaivarin Kesäkonsertti", city: "Helsinki", country: "Finland" },
  { date: "08.06.2002", venue: "Kaisaniemi Pop", city: "Helsinki", country: "Finland" },
  { date: "18.05.2002", venue: "Nite Train", city: "Imatra", country: "Finland" },
  { date: "17.05.2002", venue: "Henry's Pub", city: "Kuopio", country: "Finland" },
  { date: "11.05.2002", venue: "Tavastia", city: "Helsinki", country: "Finland" },
  { date: "10.05.2002", venue: "Hollywood", city: "Varkaus", country: "Finland" },
  { date: "09.05.2002", venue: "Vaakuna", city: "Mikkeli", country: "Finland" },
  { date: "08.05.2002", venue: "Rytmikatti", city: "Kouvola", country: "Finland" },
  { date: "07.05.2002", venue: "Lappee", city: "Lappeenranta", country: "Finland" },
  { date: "01.05.2002", venue: "Yokotai,<BR>YLE TV1 (TV)", city: "Helsinki", country: "Finland" },
  { date: "26.04.2002", venue: "Tivoli", city: "Rovaniemi", country: "Finland" },
  { date: "25.04.2002", venue: "Gina", city: "Raahe", country: "Finland" },
  { date: "24.04.2002", venue: "Foxia", city: "Oulu", country: "Finland" },
  { date: "22.04.2002", venue: "Studio B - live,<BR>Yle / Radiomafia (TV)", city: "Helsinki", country: "Finland" },
  { date: "20.04.2002", venue: "Lutakko", city: "Jyväskylä", country: "Finland" },
  { date: "19.04.2002", venue: "Yo-talo", city: "Tampere", country: "Finland" },
  { date: "18.04.2002", venue: "Kåren", city: "Turku", country: "Finland" },
  { date: "17.04.2002", venue: "Paradise Garden", city: "Salo", country: "Finland" },
  { date: "13.04.2002", venue: "Raumanlinna", city: "Rauma", country: "Finland" },
  { date: "11.04.2002", venue: "(private)", city: "Espoo", country: "Finland" },
  { date: "09.04.2002", venue: "Kimmel", city: "Joensuu", country: "Finland" },
  { date: "03.04.2002", venue: "Vekaranjärven sotilaskoti", city: "Valkeala", country: "Finland" },
  { date: "23.03.2002", venue: "Hotelli Ylivieska", city: "Ylivieska", country: "Finland" },

  // 2001
  { date: "25.10.2001", venue: "CMU San Juan Evangelista,<BR>Universidad Complutense de Madrid", city: "Madrid", country: "Spain" },
  { date: "29.08.2001", venue: "Huvilateltta", city: "Helsinki", country: "Finland" },
  { date: "18.08.2001", venue: "Popkalaset", city: "Tammisaari", country: "Finland" },
  { date: "17.08.2001", venue: "Popkalaset", city: "Porvoo", country: "Finland" },
  { date: "11.08.2001", venue: "Rock The Globe,<BR>Satamatori", city: "Kuopio", country: "Finland" },
  { date: "21.07.2001", venue: "Tyrkkyrock", city: "Jyväskylä", country: "Finland" },
  { date: "04.07.2001", venue: "Arezzo Wave 2001", city: "Arezzo", country: "Italy" },
  { date: "23.06.2001", venue: "Raumanmeren juhannus", city: "Rauma", country: "Finland" },
  { date: "23.06.2001", venue: "Rantarock", city: "Vaasa", country: "Finland" },
  { date: "22.06.2001", venue: "Mukkulan juhannus", city: "Lahti", country: "Finland" },
  { date: "22.06.2001", venue: "Midnight Party Planet,<BR>Tykkimäki", city: "Kouvola", country: "Finland" },
  { date: "17.06.2001", venue: "Provinssirock, Päätösklubi", city: "Seinäjoki", country: "Finland" },
  { date: "16.06.2001", venue: "Provinssirock,<BR>Mainland stage", city: "Seinäjoki", country: "Finland" },
  { date: "09.06.2001", venue: "DBTL", city: "Turku", country: "Finland" },
  { date: "12.05.2001", venue: "Finlandia-talo", city: "Helsinki", country: "Finland" },
  { date: "06.05.2001", venue: "Levitation, Hullu Poro Areena", city: "Sirkka", country: "Finland" },
  { date: "12.04.2001", venue: "Lo Street Club", city: "Rimini", country: "Italy" },
  { date: "11.04.2001", venue: "Barrumba", city: "Torino", country: "Italy" },
  { date: "10.04.2001", venue: "Tenax", city: "Firenze", country: "Italy" },
  { date: "31.03.2001", venue: "Network, Hippos-halli", city: "Jyväskylä", country: "Finland" },
  { date: "28.03.2001", venue: "Vekaranjärven sotilaskoti", city: "Valkeala", country: "Finland" },
  { date: "24.03.2001", venue: "Rantasipi", city: "Hyvinkää", country: "Finland" },
  { date: "03.03.2001", venue: "Polideportivo Principe Felipe", city: "Zaragoza", country: "Spain" },
  { date: "02.03.2001", venue: "Salamandra", city: "Valladolid", country: "Spain" },
  { date: "01.03.2001", venue: "La Santa Sede", city: "Oviedo", country: "Spain" },
  { date: "07.02.2001", venue: "Sala Arena", city: "Madrid", country: "Spain" },
  { date: "07.02.2001", venue: "Música sí,<BR>Estudios de Prado del Rey,<BR>RTVE (TV)", city: "Madrid", country: "Spain" },
  { date: "06.02.2001", venue: "Razzmatazz 2", city: "Barcelona", country: "Spain" },
  { date: "05.02.2001", venue: "Los conciertos de Radio 3,<BR>TV3 Sant Joan Despí", city: "Barcelona", country: "Spain" },
  { date: "03.02.2001", venue: "Emma Gaala 2000, Finlandia-talo", city: "Helsinki", country: "Finland" },
  { date: "26.01.2001", venue: "Työväentalo", city: "Kangasniemi", country: "Finland" },

  // 2000
  { date: "15.12.2000", venue: "Casino", city: "Järvenpää", country: "Finland" },
  { date: "13.12.2000", venue: "Tiiranlinna", city: "Raahe", country: "Finland" },
  { date: "12.12.2000", venue: "Radisson SAS", city: "Oulu", country: "Finland" },
  { date: "08.12.2000", venue: "Nosturi", city: "Helsinki", country: "Finland" },
  { date: "02.12.2000", venue: "Onnenpäivät", city: "Imatra", country: "Finland" },
  { date: "01.12.2000", venue: "Suomalainen klubi (private)", city: "Helsinki", country: "Finland" },
  { date: "29.11.2000", venue: "Botta (private)", city: "Helsinki", country: "Finland" },
  { date: "24.11.2000", venue: "Puuteri", city: "Hämeenlinna", country: "Finland" },
  { date: "18.11.2000", venue: "Lutakko", city: "Jyväskylä", country: "Finland" },
  { date: "17.11.2000", venue: "Mindtrek, Yo-talo", city: "Tampere", country: "Finland" },
  { date: "11.11.2000", venue: "Lapuahovi", city: "Lapua", country: "Finland" },
  { date: "10.11.2000", venue: "Kerubi", city: "Joensuu", country: "Finland" },
  { date: "09.11.2000", venue: "Tähti", city: "Kuopio", country: "Finland" },
  { date: "08.11.2000", venue: "Villikissa", city: "Iisalmi", country: "Finland" },
  { date: "02.11.2000", venue: "www.workingday.com, Vanha", city: "Helsinki", country: "Finland" },
  { date: "05.11.2000", venue: "Skiexpo, Messukeskus", city: "Helsinki", country: "Finland" },
  { date: "07.11.2000", venue: "Pikkuwappu, Foxia", city: "Oulu", country: "Finland" },
  { date: "28.10.2000", venue: "Urban Expo,<BR>Kaapelitehdas", city: "Helsinki", country: "Finland" },
  { date: "28.10.2000", venue: "Urmas-tapahtuma,<BR>Pirkkolahalli", city: "Helsinki", country: "Finland" },
  { date: "08.10.2000", venue: "Cafe Medicin Man", city: "Hyvinkää", country: "Finland" },
  { date: "06.10.2000", venue: "Areena", city: "Seinäjoki", country: "Finland" },
  { date: "05.10.2000", venue: "Raumanlinna", city: "Rauma", country: "Finland" },
  { date: "03.10.2000", venue: "Lakinlaskiaiset, Otaniemi", city: "Espoo", country: "Finland" },
  { date: "30.09.2000", venue: "Tuiskulan lava", city: "Nivala", country: "Finland" },
  { date: "29.09.2000", venue: "Club 25", city: "Vaasa", country: "Finland" },
  { date: "25.09.2000", venue: "Generation X,<BR>In The City", city: "Manchester", country: "United Kingdom" },
  { date: "23.09.2000", venue: "Akateeminen Startti", city: "Kuopio", country: "Finland" },
  { date: "22.09.2000", venue: "Kåren", city: "Turku", country: "Finland" },
  { date: "21.09.2000", venue: "Olympiateltta, Rautatientori", city: "Helsinki", country: "Finland" },
  { date: "13.09.2000", venue: "EVAMK-fuksiaiset,<BR>Vanha", city: "Helsinki", country: "Finland" },
  { date: "08.09.2000", venue: "Puhdas elämä lapselle,<BR>Olympiastadion", city: "Helsinki", country: "Finland" },
  { date: "02.09.2000", venue: "Tavastia", city: "Helsinki", country: "Finland" },
  { date: "25.08.2000", venue: "Oulu Music Video Festival,<BR>45 Special", city: "Oulu", country: "Finland" },
  { date: "25.08.2000", venue: "The 5th Annual Air Guitar World Championships,<BR>Oulu Music Video Festival,<BR>Oulun tori", city: "Oulu", country: "Finland" },
  { date: "22.08.2000", venue: "Ravintola Hullu Kukko,<BR>Forum (private)", city: "Helsinki", country: "Finland" },
  { date: "19.08.2000", venue: "Sarjakuvafestivaali,<BR>VR:n makasiinit", city: "Helsinki", country: "Finland" },
  { date: "18.08.2000", venue: "Pluto 2000,<BR>Art & Music Festival", city: "Pietarsaari", country: "Finland" },
  { date: "12.08.2000", venue: "Paltamon syysrysäys", city: "Paltamo", country: "Finland" },
  { date: "06.08.2000", venue: "Ankkarock", city: "Korso", country: "Finland" },
  { date: "04.08.2000", venue: "Koneisto", city: "Turku", country: "Finland" },
  { date: "29.07.2000", venue: "Down By The Kemijoki,<BR>Tivoli", city: "Rovaniemi", country: "Finland" },
  { date: "22.07.2000", venue: "Koriaroll", city: "Koria", country: "Finland" },
  { date: "16.07.2000", venue: "Tammerfest<BR>YO-talo", city: "Tampere", country: "Finland" },
  { date: "08.07.2000", venue: "Ilosaarirock", city: "Joensuu", country: "Finland" },
  { date: "24.06.2000", venue: "Himos Festival", city: "Jämsä", country: "Finland" },
  { date: "23.06.2000", venue: "Midnight Party Planet,<BR>Tykkimäki", city: "Kouvola", country: "Finland" },
  { date: "23.06.2000", venue: "Raumanmeren juhannus", city: "Rauma", country: "Finland" },
  { date: "22.06.2000", venue: "Hangon juhannus", city: "Hanko", country: "Finland" },
  { date: "17.06.2000", venue: "Provinssirock", city: "Seinäjoki", country: "Finland" },
  { date: "12.06.2000", venue: "Espan lava", city: "Helsinki", country: "Finland" },
  { date: "10.06.2000", venue: "Olen niin pop!<BR>Radiomafian 10-vuotiskonsertti", city: "Helsinki", country: "Finland" },
  { date: "09.06.2000", venue: "DBTL", city: "Turku", country: "Finland" },
  { date: "08.06.2000", venue: "Razorfish (Private)", city: "Helsinki", country: "Finland" },
  { date: "03.06.2000", venue: "Club 25", city: "Vaasa", country: "Finland" },
  { date: "27.05.2000", venue: "Offrock", city: "Kausala", country: "Finland" },
  { date: "25.05.2000", venue: "Ravintola Motti", city: "Helsinki", country: "Finland" },
  { date: "23.05.2000", venue: "Muotinäytös, Pravda", city: "Helsinki", country: "Finland" },
  { date: "19.05.2000", venue: "Club Moo", city: "Pori", country: "Finland" },
  { date: "18.05.2000", venue: "Tähti", city: "Kuopio", country: "Finland" },
  { date: "11.05.2000", venue: "Akatateeminen Vartti,<BR>Vanha", city: "Helsinki", country: "Finland" },
  { date: "09.05.2000", venue: "Nosturi (private)", city: "Helsinki", country: "Finland" },
  { date: "29.04.2000", venue: "Stiller,<BR>Nelonen (TV)", city: "Helsinki", country: "Finland" },
  { date: "21.04.2000", venue: "Tavastia", city: "Helsinki", country: "Finland" },
  { date: "15.04.2000", venue: "Onnenpäivät", city: "Imatra", country: "Finland" },
  { date: "14.04.2000", venue: "Kuntotalo", city: "Mikkeli", country: "Finland" },
  { date: "13.04.2000", venue: "City-Anttila Megastore", city: "Helsinki", country: "Finland" },
  { date: "10.04.2000", venue: "Semifinal,<BR>(album release party)", city: "Helsinki", country: "Finland" },
  { date: "10.04.2000", venue: "Upteekki,<BR>YLE / Radiomafia,(Radio, unplugged)", city: "Helsinki", country: "Finland" },
  { date: "31.03.2000", venue: "Yo-talo", city: "Tampere", country: "Finland" },
  { date: "03.03.2000", venue: "Nosturi", city: "Helsinki", country: "Finland" },
  { date: "25.02.2000", venue: "Bella Donna", city: "Seinäjoki", country: "Finland" },
  { date: "24.02.2000", venue: "7 päivää syntymäpäivät", city: "Helsinki", country: "Finland" },
  { date: "04.02.2000", venue: "Kåren", city: "Turku", country: "Finland" },
  { date: "30.01.2000", venue: "DDR,<BR>YLE / Radio Extrem (Radio)", city: "Helsinki", country: "Finland" },
  { date: "26.01.2000", venue: "Kipsari", city: "Helsinki", country: "Finland" },
  { date: "22.01.2000", venue: "Gloria", city: "Helsinki", country: "Finland" },
  { date: "09.01.2000", venue: "Jump Inn", city: "Helsinki", country: "Finland" },

  // 1999
  { date: "12.12.1999", venue: "Cafe Medicin Man", city: "Hyvinkää", country: "Finland" },
  { date: "30.11.1999", venue: "Jyrki, MTV3, Lasipalatsi (TV)", city: "Helsinki", country: "Finland" },
  { date: "25.11.1999", venue: "Kaapelitehdas, (private)", city: "Helsinki", country: "Finland" },
  { date: "24.11.1999", venue: "Bar 33", city: "Helsinki", country: "Finland" },
  { date: "11.11.1999", venue: "Jump Inn", city: "Helsinki", country: "Finland" },
  { date: "16.10.1999", venue: "Vuosaaren telakka, (private)", city: "Helsinki", country: "Finland" },
  { date: "09.10.1999", venue: "Uusi yo-talo", city: "Helsinki", country: "Finland" },
  { date: "11.09.1999", venue: "Saunabar", city: "Helsinki", country: "Finland" },
  { date: "26.08.1999", venue: "Kahvila Piritta", city: "Helsinki", country: "Finland" },
  { date: "17.06.1999", venue: "Blue Room", city: "Helsinki", country: "Finland" },
  { date: "04.06.1999", venue: "Lepakko", city: "Helsinki", country: "Finland" },
  { date: "03.05.1999", venue: "Ääni ja vimma, Gloria", city: "Helsinki", country: "Finland" },
  { date: "09.04.1999", venue: "Ääni ja vimma,<BR>Kettutien nuorisotalo", city: "Helsinki", country: "Finland" },
  { date: "18.03.1999", venue: "Espoo–Vantaa Polytechnic", city: "Espoo", country: "Finland" }
];
